# 全局配置:
api: 
  setting: 
    btcdo: 
      apiKey: AAAAAYax9qXXXXXXJ2R27f5Eg629bJt3
      apiSecret: n6qKwe7XXXX8udkJShyP
      restApiEndpoint: https://xxx.btcdo.org
# logging config:
logging:
  level:
    crypto.log: INFO
    com.itranswarp.warpdb.WarpDb: DEBUG
# WebSocket配置
websocket:
      uri: wss://xxx.btcdo.com/v1/market/?EIO=3&transport=websocket