# 全局配置:
api: 
  setting: 
    btcdo: 
      #登录Btcdo账户，在“个人中心”→“安全中心”获取API-KEY和API-SECRET
      apiKey: 您的APIKEY
      apiSecret: 您的APISECRET
      restApiEndpoint: https://api.btcdo.com
# logging config:
logging:
  level:
    crypto.log: INFO
    com.itranswarp.warpdb.WarpDb: DEBUG
# WebSocket配置
websocket:
      uri: wss://onli-quotation.btcdo.com/v1/market/?EIO=3&transport=websocket
